name: Islands
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  splash_screen_view: ^3.0.0
  provider: ^6.0.3
  google_nav_bar: ^5.0.6
  ionicons: ^0.1.2
  http: ^0.13.4
  skeleton_text: ^3.0.0
  webview_flutter_plus: ^0.3.0+2
  url_launcher: ^6.1.4
  whatsapp_unilink: ^2.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Renogare
      fonts:
        - asset: assets/fonts/Renogare/Renogare-Regular.otf
    - family: TypoGrotesk
      fonts:
        - asset: assets/fonts/Typo_Grotesk/TypoGrotesk.otf
        